-- MySQL Script generated by MySQL Workbench
-- Tue Mar 17 15:34:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema naming
-- -----------------------------------------------------
-- DROP SCHEMA IF EXISTS `naming` ;

-- -----------------------------------------------------
-- Schema naming
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `naming` DEFAULT CHARACTER SET utf8 ;
USE `naming` ;

-- -----------------------------------------------------
-- Table `naming`.`accsystem`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `naming`.`accsystem` ;

CREATE TABLE IF NOT EXISTS `naming`.`accsystem` (
  `system_id` INT NOT NULL AUTO_INCREMENT,
  `system_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`system_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `naming`.`subsystem`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `naming`.`subsystem` ;

CREATE TABLE IF NOT EXISTS `naming`.`subsystem` (
  `subsystem_id` INT NOT NULL AUTO_INCREMENT,
  `subsystem_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`subsystem_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `naming`.`device`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `naming`.`device` ;

CREATE TABLE IF NOT EXISTS `naming`.`device` (
  `device_id` INT NOT NULL AUTO_INCREMENT,
  `system_id` INT NOT NULL,
  `seq_number` INT NULL DEFAULT NULL,
  `English_name` VARCHAR(100) NULL DEFAULT NULL,
  `Chinese_name` VARCHAR(100) NULL DEFAULT NULL,
  `design_name` VARCHAR(45) NULL DEFAULT NULL,
  `remark` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`device_id`),
  INDEX `fk_device_system1_idx` (`system_id` ASC),
  CONSTRAINT `fk_device_system1`
    FOREIGN KEY (`system_id`)
    REFERENCES `naming`.`accsystem` (`system_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `naming`.`more_than_nine`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `naming`.`more_than_nine` ;

CREATE TABLE IF NOT EXISTS `naming`.`more_than_nine` (
  `judge_id` INT NOT NULL AUTO_INCREMENT,
  `yes_or_no` VARCHAR(40) NULL DEFAULT NULL,
  `another_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`judge_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `naming`.`location`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `naming`.`location` ;

CREATE TABLE IF NOT EXISTS `naming`.`location` (
  `location_id` INT NOT NULL AUTO_INCREMENT,
  `judge_id` INT NOT NULL,
  `location_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`location_id`),
  INDEX `fk_location_more_than_nine1_idx` (`judge_id` ASC),
  CONSTRAINT `fk_location_more_than_nine1`
    FOREIGN KEY (`judge_id`)
    REFERENCES `naming`.`more_than_nine` (`judge_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `naming`.`device_subsystem_location`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `naming`.`device_subsystem_location` ;

CREATE TABLE IF NOT EXISTS `naming`.`device_subsystem_location` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subsystem_id` INT NOT NULL,
  `location_id` INT NOT NULL,
  `device_id` INT NOT NULL,
  INDEX `fk_re_subsystem_location_subsystem1_idx` (`subsystem_id` ASC),
  INDEX `fk_re_subsystem_location_location1_idx` (`location_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_re_subsystem_location_device1_idx` (`device_id` ASC),
  CONSTRAINT `fk_re_subsystem_location_subsystem1`
    FOREIGN KEY (`subsystem_id`)
    REFERENCES `naming`.`subsystem` (`subsystem_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_re_subsystem_location_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `naming`.`location` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_re_subsystem_location_device1`
    FOREIGN KEY (`device_id`)
    REFERENCES `naming`.`device` (`device_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=1;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
